# Alacritty Configuration
env:
  TERM: xterm-256color

alt_send_esc: false
live_config_reload: true
debug:
  render_timer: false
  persistent_logging: false
  log_level: Debug
  print_events: false
  ref_test: false
  print_events: false
  ref_test: false

window:
  dimensions:
    columns: 150
    lines: 70
  padding:
    x: 0
    y: 0
  dynamic_padding: false

scrolling:
  history: 10000

decorations: full
# font_family: &family "Liberation Mono"
font_family: &family "Mensch"

font:
  size: 14
  normal:
    family: *family
    style: "Regular"
  bold:
    family: *family
    style: "Bold"
  italic:
    family: *family
    style: "Italic"
  bold_italic:
    family: *family
    style: "Bold Italic"

colors:
  primary:
    background: '0x000000'
    foreground: '0xffffff'

  normal:
    black:   '0x10100e'
    red:     '0xcd0000'
    green:   '0x00cd00'
    yellow:  '0xcdcd00'
    blue:    '0x0087bd'
    magenta: '0xcd00cd'
    cyan:    '0x00cdcd'
    white:   '0xe5e5e5'

  bright:
    black:   '0x696969'
    red:     '0xcd0000'
    green:   '0x00ff00'
    yellow:  '0xfdff00'
    blue:    '0x007fff'
    magenta: '0xff00ff'
    cyan:    '0x00ffff'
    white:   '0xffffff'

use_thin_strokes: false
draw_bold_text_with_bright_colors: false

bell:
  animation: EaseOutExpo
  duration: 0
  color: '#FFFFFF'

# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
custom_cursor_colors: true

unfocused_hollow: true
# cursor:
#   style: Block

selection:
  semantic_escape_chars: ",`|:\"'()[]{}<>\t\n"
  dynamic_title: true

mouse_bindings:
 - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 275 }
  triple_click: { threshold: 275 }
  hide_when_typing: true

# Key Bindings:
key_bindings:
  - { key: Paste, action: Paste}
  - { key: Copy, action: Copy}

